default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: progressive_timetable_development
  username: %USERNAME%
  password: %PASSWORD%

test:
  <<: *default
  database: progressive_timetable_test
  username: %USERNAME%
  password: %PASSWORD%

production:
  <<: *default
  database: progressive_timetable_production
  username: %USERNAME%
  password: %PASSWORD%