# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1aa028220fc80764bf62236427f722cccf463f377934073c371376ba99adc38f0e54a18b5ff8d92a6e83509d1e5795e9414e5bae81fc96610383b6c15eab37fa

test:
  secret_key_base: 1a9b8b8663c6ae7e3d2396a1efa7dfedc3a61c0e6e9d1417d56240dbdf555ac680afb2e9db27a3c3be42e3a7fded3a8dca5d5d9d6f98a5128d96d3ed91362ffd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
